clap_select:
  student:
    name: "学生服务"
    options:
      - "学生信息列表"
      - "添加学生信息"
      - "修改学生信息"
      - "删除学生信息"
      - "退出"
  class:
    name: "班级服务"
  course:
    name: "学科服务"
  club:
    name: "社团服务"